name: dart_ext
version: 1.0.0
author: Kun Zhao <kunzhao77@gmail.com>
description: A set of useful helper functions to making collection, string and function easier to use
homepage: https://github.com/kzhdev/dart_ext
environment:
  sdk: '>=1.24.0 <2.0.1'

dev_dependencies:
  test: ^0.12.0
