name: dart_ext
version: 0.0.7
author: Kun Zhao <kzhdev@gmail.com>
description: A set of useful helper functions
homepage: https://github.com/kzhdev/dart_ext
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
